#!/bin/bash
ac=$(command -v acpi)
if [ -z $ac ]
then
    batt="No ACPI"
else
    batt=$(acpi) 
    batt=$(echo $batt | sed -e "s/Battery [0-9]\: //")
    batt=$(echo $batt | sed -e "s/Discharging, /-|/") 
    batt=$(echo $batt | sed -e "s/Charging, /+|/") 
    batt=$(echo $batt | sed -e "s/, / /")
    batt=$(echo $batt | sed -e "s/ remaining//")
    batt=$(echo $batt | sed -e "s/ until charged//")
    batt=$(echo $batt | sed -e  "s/\([0-9][0-9]\:[0-9][0-9]\)\:[0-9][0-9]/\1/")
    batt=$(echo $batt | sed -e  "s/\([0-9][0-9]\:[0-9][0-9]\)/\1m/")
    batt=$(echo $batt | sed -e  "s/\:/h /")
    batt=$(echo $batt | sed -e  "s/Unknown/Bat:/")
fi
echo $batt 
