#!/bin/bash
muted=$(awk '/muted/ {print $2}' <(pacmd list-sinks))
if [ $muted != "yes" ]
then
    volume=$(awk '/volume/ {print $5;exit}' <(pacmd list-sinks))
    echo "Vol|"$volume
else
    echo "Muted"
fi
