#!/bin/bash
pa=$(command -v pacmd)
if [ -z $pa  ]
then
    echo "No Pacmd"
else
    sinks="$(pulseaudio --check)"
    if [[ $sinks == "" ]]
    then
        muted=$(awk '/muted/ {print $2}' <(pacmd list-sinks))
        if [[ $muted != "yes" ]]
        then
            volume=$(awk '/volume/ {print $5;exit}' <(pacmd list-sinks))
            echo "|"$volume
        else
            echo ""
        fi
    else
        echo "No Daemon"
    fi
fi

