#!/bin/bash
sinks=$(command -v pacmd)
if [ -z $sinks  ]
then
    echo "No Pacmd"
else
muted=$(awk '/muted/ {print $2}' <(pacmd list-sinks))
if [ $muted != "yes" ]
then
    volume=$(awk '/volume/ {print $5;exit}' <(pacmd list-sinks))
    echo "|"$volume
else
    echo ""
fi
fi
